apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: devops-ns
spec:
  version: 7.9.1
  count: 1
  secureSettings:
  - secretName: apm-secret-settings
  config:
    output:
      elasticsearch:
        hosts: ["elastic-es-http.devops-ns:9200"]
        username: elastic
        password: "${ES_PASSWORD}"
        protocol: "https"
        ssl.certificate_authorities: ["/usr/share/apm-server/config/elasticsearch-ca/tls.crt"]
  podTemplate:
      spec:
        containers:
        - name: apm-server
          volumeMounts:
          - mountPath: /usr/share/apm-server/config/elasticsearch-ca
            name: elasticsearch-ca
            readOnly: true
        volumes:
        - name: elasticsearch-ca
          secret:
            defaultMode: 420
            optional: false
            secretName: elastic-es-http-ca-internal # This is the secret that holds the Elasticsearch CA cert
  http:
    service:
      metadata:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: apm.${ENV}.${ROOT_INFRA_DOMAIN}
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        creationTimestamp: null
      spec:
        type: LoadBalancer
    tls:
      certificate: {}
