---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
  ##namespace: default
  labels:
    env: vault-certmanager-tryouts
spec:
  vault:
    path: ${PATH}
    server: "http://${resource_prefix}-eks-vault-${ENV}-ui:8200"
    #caBundle: <base64 encoded caBundle PEM file>
    auth:
      tokenSecretRef:
          name: vault-root-token
          key: secret-token