---

- name: Create Kubernetes addon directory
  file:
    path: "{{ network_dir }}"
    state: directory

- name: Download {{ network }} yaml
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: "{{ network_dir }}/files.yml"
    mode: '0440'

- name: "Check {{ network }} daemonset is working"
  shell: kubectl --kubeconfig={{ kubeadmin_config }} get ds --all-namespaces | grep {{ network }}
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: check_net
  ignore_errors: true
  changed_when: false


- name: "Create {{ network }} network daemonset"
  when: check_net is failed
  command: kubectl apply --kubeconfig={{ kubeadmin_config }} -f {{ network_dir }}/files.yml
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
