name: Destroy environment sandbox

on:
  workflow_dispatch:
    inputs:
      environment_sets:
        description: 'Terraform variable sets'
        required: true
        default: 'sandbox'
      action:
        description: 'Action to deploy (cidestroy, ciplan, validadte)'
        required: true
        default: 'cidestroy'
env:
  INFRA_UNIT_DIR:  ${{  github.workspace }}/terraform/cloud-aws/src/projects/
  AWS_ACCESS_KEY_ID:  ${{   secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{   secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION:  ${{   secrets.AWS_DEFAULT_REGION }}
jobs:
  init-environment:
    runs-on: ubuntu-latest #linux-platform # linux-platform, ubuntu-latest
  

    steps:
    - uses: actions/checkout@v2

    ###################################################
    ###################################################
    - name: HashiCorp - Setup Terraform
      # You may pin to the exact commit or the version.
      # uses: hashicorp/setup-terraform@15ba5bd056f1f2406e37023ca22c75ca08ceeb6e
      uses: hashicorp/setup-terraform@v1.3.2
      with:
        terraform_version: "1.0.11"

    - name: AWS cli install action
      # You may pin to the exact commit or the version.
      # uses: chrislennon/action-aws-cli@1347f1da2852be38fdbea5e6e336f1e297fec7a0
      uses: chrislennon/action-aws-cli@1.1

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v1


  ###################################################
  ###################################################
    - name: Uninstalling External access
      shell: bash        
      run: |
        cd terraform
        ./tf.sh ${{github.event.inputs.environment_sets}} 7.1.external-access ${{github.event.inputs.action}}
    - name: Install EKS Security (Consul, Vault, Certmanager)
      run: |
        cd terraform      
        ./tf.sh ${{github.event.inputs.environment_sets}} 4.1.6.security ${{github.event.inputs.action}}
    - name: Uninstalling EKS Istio
      run: |
        cd terraform      
        ./tf.sh ${{github.event.inputs.environment_sets}} 4.1.4.istio ${{github.event.inputs.action}}
    - name: Uninstalling EKS Observability (prometheus, thanos,)
      run: |
        cd terraform      
        ./tf.sh ${{github.event.inputs.environment_sets}} 4.1.3.observability ${{github.event.inputs.action}}
    - name: Uninstalling EKS Services (metrics, external-dns, etc..)
      run: |
        cd terraform      
        ./tf.sh ${{github.event.inputs.environment_sets}} 4.1.2.services ${{github.event.inputs.action}}
    - name: Uninstalling eks
      run: |
        cd terraform      
        ./tf.sh ${{github.event.inputs.environment_sets}} 4.1.1.eks ${{github.event.inputs.action}}


    - name: Uninstalling Log config
      run: |
        cd terraform      
        ./tf.sh ${{github.event.inputs.environment_sets}} 3.4.management ${{github.event.inputs.action}}
  
    - name: Uninstalling Log config
      run: |
        cd terraform      
        ./tf.sh ${{github.event.inputs.environment_sets}} 3.2.log-shipping ${{github.event.inputs.action}}
  
    - name: Uninstalling DNS
      run: |
        cd terraform      
        ./tf.sh ${{github.event.inputs.environment_sets}} 3.1.dns-base ${{github.event.inputs.action}}
    - name: Uninstalling VPC
      run: |
        cd terraform      
        ./tf.sh ${{github.event.inputs.environment_sets}} 2.vpc ${{github.event.inputs.action}}
    - name: Uninstalling Init Dependencies
      run: |
        cd terraform      
        ./tf.sh ${{github.event.inputs.environment_sets}} 1.init ${{github.event.inputs.action}}
    - name: Uninstalling sso
      run: |
        cd terraform      
        ./tf.sh ${{github.event.inputs.environment_sets}} 0.sso ${{github.event.inputs.action}}

 
 
