name: CI main

on:
  push:
    branches: [ main ]

env:
  PROJECT_NAME: "api-flask-1"
  AWS_ACCESS_KEY_ID:  ${{   secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{   secrets.AWS_SECRET_ACCESS_KEY }}
  PROXY_ENABLE: true
  PRERELEASE: ${{ secrets.PRERELEASE }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Origin"
      uses: actions/checkout@v2

    - uses: chrisdickinson/setup-yq@latest
      with:
        yq-version: 2.4.1
        yq-url: https://github.com/mikefarah/yq/releases/download/{version}/yq_{platform}_amd64


    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV


    - name: Checking new version based commits
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: main
        dry_run: true
        append_to_pre_release_tag: ${{ env.SHORT_SHA }}



    - name: Add & Commit
      uses: EndBug/add-and-commit@v7.0.0
      with:
        message: "RELEASE-Autoupgrade new chart version ${{steps.tag_version.outputs.new_version}}"

    - name: "Get build info"
      id: build_info
      shell: bash
      run: |
    
        python -m venv .changelog
        source .changelog/bin/activate
        pip install -e "git+https://${{ secrets.ACTIONS_TOKEN }}@github.com/tpaxle/python-app-changelog.git#egg=changelog"

        release_body=`changelog ${GITHUB_REPOSITORY} -t ${{ github.token }} -sr v${{steps.tag_version.outputs.previous_tag}} -b main`
        release_body="${release_body//'%'/%25}"
        release_body="${release_body//$'\n'/%0A}"
        release_body="${release_body//$'\r'/%0D}"
        echo "##[set-output name=release_body;]$(echo ${release_body})"
        deactivate

    - name: "Create release"
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      with:
        tag_name: ${{steps.tag_version.outputs.new_tag}}
        release_name: Release ${{steps.tag_version.outputs.new_tag}}
        body: |
          ${{steps.build_info.outputs.release_body}}
        draft: false
        prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}        
  upload-assests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1.64.1
      env:
        ImageOS: ubuntu18
      with:
        bundler-cache: true
        ruby-version: '2.6'

    - name: "Acciidoctor-pdf"
      run: |
        bundle exec asciidoctor-pdf README.adoc -a pdf-theme=first.yml -a pdf-stylesdir=docs/themes/
      
    - name: Create zip file
      run: zip -r ansible-playbook-k8s.zip README.pdf

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ GITHUB.token }}
      with:
        upload_url: ${{ needs.build.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ansible-playbook-k8s.zip
        asset_name: ansible-playbook-k8s.zip
        asset_content_type: application/zip
